{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "code-marketplace.fullname" . }}
spec:
  podSelector:
    matchLabels:
      {{- include "code-marketplace.selectorLabels" . | nindent 6 }}
    matchExpressions:
      - key: app.kubernetes.io/component
        operator: In
        values:
          - marketplace
          - importer
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - ports:
        - protocol: TCP
          port: {{ .Values.service.targetPort }}
      from:
        {{- toYaml .Values.networkPolicy.ingressFrom | nindent 8 }}
  egress:
    {{- toYaml .Values.networkPolicy.egress | nindent 4 }}
{{- if .Values.tests.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "code-marketplace.fullname" . }}-test
spec:
  podSelector:
    matchLabels:
      {{- include "code-marketplace.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: test
  policyTypes:
    - Ingress
    - Egress
  ingress: []
  egress:
    - to:
        - podSelector:
            matchLabels:
              {{- include "code-marketplace.selectorLabels" . | nindent 14 }}
              app.kubernetes.io/component: marketplace
      ports:
        - protocol: TCP
          port: {{ .Values.service.targetPort }}
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
{{- end }}
{{- end }}
