name: lint/helm

on:
  push:
    branches:
      - main
    paths:
      - "helm/**"
      - ".github/workflows/helm.yaml"
  pull_request:
    paths:
      - "helm/**"
      - ".github/workflows/helm.yaml"
  workflow_dispatch:

# Cancel in-progress runs for pull requests when developers push
# additional changes
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  lint:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.0
      - uses: azure/setup-helm@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: helm lint --strict ./helm
      - run: helm lint --strict ./helm -f ./helm/values-offline.yaml
      - run: helm lint --strict ./helm -f ./helm/values-offline.yaml -f ./helm/values-admin.yaml
      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - run: |
          helm template marketplace ./helm > /tmp/marketplace-default.yaml
          helm template marketplace ./helm -f ./helm/values-offline.yaml --set tests.enabled=true > /tmp/marketplace-offline.yaml
          helm template marketplace ./helm -f ./helm/values-offline.yaml -f ./helm/values-admin.yaml > /tmp/marketplace-admin.yaml
          go run github.com/yannh/kubeconform/cmd/kubeconform@v0.7.0 -strict -summary -kubernetes-version 1.31.0 /tmp/marketplace-default.yaml /tmp/marketplace-offline.yaml /tmp/marketplace-admin.yaml
